name: 'docker-build-action'
description: 'Simplified Docker image builds with Github Actions.'
inputs:
  tags:
    description: 'Enter the tag you would like to name your image with. (example: myorg/myapp:production)'
    required: true
  registry-username:
    description: 'Enter the username to authenticate with your registry.'
    default: ''
  registry-password:
    description: 'Enter the password or token to authenticate with your registry. (an access token is highly recommended)'
    default: ''
  registry-token:
    description: '[DEPRECATED - Use registry-password instead] Enter the token or password to authenticate with your registry. (an access token is highly recommended)'
    default: ''
  registry:
    description: 'Registry to authenticate with (e.g., "docker.io" or "ghcr.io").'
    default: 'docker.io' # Default to Docker Hub if not specified
    required: false
  registry-username-2:
    description: 'Enter the username to authenticate with your registry.'
    default: ''
  registry-password-2:
    description: 'Enter the token or password to authenticate with your registry. (an access token is highly recommended)'
    default: ''
  registry-2:
    description: 'Registry to authenticate with (e.g., "docker.io" or "ghcr.io").'
  registry-username-3:
    description: 'Enter the username to authenticate with your registry.'
    default: ''
  registry-password-3:
    description: 'Enter the token or password to authenticate with your registry. (an access token is highly recommended)'
    default: ''
  registry-3:
    description: 'Registry to authenticate with (e.g., "docker.io" or "ghcr.io").'
  context:
    description: 'The relative path to the Dockerfile.'
    default: '.'
    required: false
  dockerfile:
    description: 'Filename of the Dockerfile within the context that you set.'
    default: './Dockerfile'
    required: false
  target:
    description: 'Set the target build stage to build.'
    default: ''
    required: false
  platforms:
    description: 'Comma separated list of platforms.'
    default: 'linux/amd64'
    required: false
runs:
  using: 'composite'
  steps:

      - name: Login to Container Registry ({{ inputs.registry }})
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.registry-username }}
          password: ${{ inputs.registry-password || inputs.registry-token }}
          registry: ${{ inputs.registry }}

      - name: "Login to Container Registry #2 ({{ inputs.registry-2 }})"
        if: inputs.registry-2-username != ''
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.registry-username-2 }}
          password: ${{ inputs.registry-password-2 }}
          registry: ${{ inputs.registry-2 }}

      - name: "Login to Container Registry #3 ({{ inputs.registry-3 }})"
        if: inputs.registry-3-username != ''
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.registry-username-3 }}
          password: ${{ inputs.registry-password-3 }}
          registry: ${{ inputs.registry-3 }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
          file: ${{ inputs.dockerfile }}
          pull: true
          push: true
          tags: ${{ inputs.tags }}
          target: ${{ inputs.target }}
branding:
  icon: 'server'
  color: 'blue'
